# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9818021fbe3b14b0fb2bbdc399c77936f943d5d342ff4443931d91eee4bf1d366965ddfccb38c29a3639b4f1087d133c558a1fb007dd145aa727bd03cf0f5b0

test:
  secret_key_base: 35ce95c6503a61ac92af91349353f037e48343ca8ee1563a573617ebc885fad9a58870fdffba184be0e43a8346e82c4604a3920b05f47eff56e7036a54fa5f14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
